# **Laboratorio 1: Una introducción a NumPy**

**Facultad de ingeniería**

Departamento de Ingeniería Biomédica

Universidad de los Andes

**IBIO-2340:** Fundamentos del machine learning

**Nombres de los integrantes**


1.   Nombre integrante 1
2.   Nombre integrante 2

**Número del grupo**

*Escribir el número del grupo*


# **1. Funciones en Python**

Para cada uno de los siguientes problemas, implemente una función que los resuelva. No puede utilizar ninguna librería externa de Python como NumPy o Scipy con métodos preestablecidos para resolverlos. Cada definición de la función deberá probarla con un ejemplo para validar la solución.

**1.1. Escriba una función que reciba como argumento una lista con números y retorne la suma de todos los números dentro de la misma.**

: 

**1.2. Escriba una función que reciba como argumento un numero entero positivo y retorne el factorial del mismo.**

**Nota:** Recuerde que el factorial de un número está dado por la siguiente fórmula:

\begin{align}
        n! = n * (n-1) * (n-2) * (n-3) * ... *(1)
\end{align}

**1.3. Escriba una función que reciba como argumento una lista con números y retorne el promedio ponderado de los números dentro de la misma. Asuma que cada elemento tiene como peso su índice dentro de la lista (el elemento 0 tiene peso 0).**

# **2. ¿Que es NumPy?**

NumPy es una de las librerías más utilizadas. Esta permite realizar desde operaciones matriciales simples hasta complejas transformadas para el procesamiento de señales. Su utilidad en la programación científica radica en la facilidad que ofrece a la hora de realizar operaciones algebraicas complicadas como diagonalización de matrices, y el cálculo de valores y vectores propios. A continuación se detallará más algunas de las principales y más útiles funciones de esta libreria que serán de utilidad dentro del curso:

En primer lugar, vamos a iniciar instalando y/o importando la libreria numpy en nuestro ambiente.

Si trabaja en **Windows**:
1. Active su entorno virtual usando el comando:
    ```bash 
    .\venv\Scripts\activate
2. Una vez en el entorno virtual instale numpy usando pip con el comando:
    ```bash
    pip install numpy
Si trabaja en **Linux** o **MacOS**:
1. Active su entorno virtual usando el comando: 
    ```bash
    source .venv/bin/activate
2. Una vez en el entorno virtual instale numpy usando pip con el comando:
    ```bash
    pip install numpy

In [ ]:
"""
Nota: El siguiente fragmento de código detecta si NumPy está instalado en su sistema y en caso de no ser así,
procede con la instalación automáticamente.

NO SE DEBE MODIFICAR ESTE FRAGMENTO.


"""

try:
  import numpy as np
  print(f"NumPy versión {np.__version__} se encuentra instalada en su sistema.")
except ImportError:
  print("NumPy no encontrado en su sistema. Verifique la instalación de Numpy.")

**Nota:** NumPy posee varias funciones que son de utilidad operando arreglos. A continuación se detallan algunas:

**np.mean:** Retorna el promedio aritmético de un arreglo numérico.

**np.std:** Retorna la desviación estandar de un arreglo numérico.

**np.sum:** Retorna la suma de todos los números cotenidos en un arreglo.

**np.prod:** Retorna la multiplicación de todos los números contenidos en un arreglo.


De la misma manera, NumPy contiene distintos módulos orientados a campos específicos. Por ejemplo, el módulo *np.math* contiene funciones básicas como factorial, combinatorias, exponencial, etc. También el módulo *np.linalg* que contiene implementaciones que permiten distintas operaciones dentro del campo del álgebra lineal que veremos más adelante.

**2.1. A continuación, repita los puntos 1.1, 1.2 y 1.3 pero utilice NumPy para sus implementaciones.**


In [5]:
#Repetición punto 1.1

In [6]:
#Repetición punto 1.2

In [7]:
#Repetición punto 1.3

#**3. Arrays en numpy**

Dentro de NumPy, una de los principales elementos son los *ndarrays* o simplemente **numpy arrays**, una estructura de datos similar a la lista tradicional de Python pero que permite mayor versatilidad a la hora de realizar operaciones. Los arrays son útiles a la hora de representar información como vectores y matrices.

Para iniciar un vector con los números de 1 a 5 se utiliza la instrucción 'np.array()' de la siguiente manera:



In [ ]:
vector = np.array([1,2,3,4,5])
print(vector)

De la misma manera, una matriz puede ser iniciada como un arreglo de arreglos según el número de dimensiones que se requiere. Por ejemplo, para iniciar una matriz de 2x2 que contenga los números de 1 a 4 se debe realizar lo siguiente:

In [ ]:
matriz = np.array([[1,2],[3,4]])
print(matriz)
print(matriz.shape)

Como se ve en la celda anterior, todos los arrays tienen un atributo denominado *shape*, que le indica al usuario las dimensiones del objeto, o lo que es lo mismo, el número de objetos en un vector o de filas y columnas en una matriz.

Así como los arrays tienen un atributo denominado shape, existen diferentes atributos que dan más información acerca del array. Acá se detallan algunos de los más comunes:

**array.ndim:** Especifica el número de dimensiones de un array. 1 en el caso de un vector, 2 en el caso de una matriz.

**array.size:** Retorna el número de elementos dentro de un array.

**array.T:** Retorna el array transpuesto.

Algunos ejemplos de estos atributos se ven a continuación:

In [ ]:
print("Numero de dimensiones en nuestra matriz:", matriz.ndim)
print("Numero de elementos en nuestra matriz:", matriz.size)
print("Matriz transpuesta de nuestra matriz:\n", matriz.T)

**3.1. Indexación de arrays de numpy**


La indexación es conocida como el proceso para obtener el elemento en una determinada posición dentro de un arreglo (array, lista). Para ello se utilizan los paréntesis cuadrados ([]) para indicar la posición de la que se quiere extraer el valor. En NumPy la indexación es similar a la realizada sobre listas con un ligero cambio.

Cuando se tiene un vector cualquier posición puede ser obtenida simplemente indicando el nombre del vector y la posición deseada. Por ejemplo:

In [ ]:
vector = np.array([1,2,3,4,5])
print(vector[2])

Por otra parte, en el caso de las matrices usualmente se realiza con una doble indexación en el caso de las listas de listas de Python. Esta manera cambia un poco dentro de los arrays, donde se debe indicar dentro de los paréntesis cuadrados las "coordenadas" del elemento que queremos. Se debe tener en cuenta que al igual que en las listas de listas la primer coordenada indica la fila mientras que la segunda coordenada indica la columna. Por ejemplo:

In [ ]:
matriz = np.array([[1,2],[3,4]])
print(matriz[0,1])

De la misma manera, si se desea obtener varios elementos se puede hacer uso de la indexación con coordenadas en conjunto con el elemento ":" (dos puntos), donde el número a la izquierda indica la posición inicial y el número a la derecha indica la posición final + 1. Por ejemplo:

```
vector[:]  #Devuelve todos los elementos del vector
vector[2:5] #Devuelve los elementos de la segunda a la cuarta posición
vector[:5] #Devuelve los elementos desde la primera hasta la cuarta posición.
vector[2:] #Devuelve los elementos a partir de la segunda posición hasta el final.
vector[::2] #Devuelve los elementos del primero al último con pasos de 2 posiciones.
vector[2:5:2] #Devuelve los elementos de la posición dos a la posición cuatro con pasos de 2.
```

En matrices se realiza la misma operación según las filas y columnas que se quieren. Por ejemplo:

```
matriz[:,:]  #Devuelve todos los elementos de tanto filas como columnas
matriz[2:5,:] #Devuelve los elementos de la segunda a la cuarta fila y todas las columnas
matriz[:,:5] #Devuelve los elementos para todas las filas desde la primera hasta la cuarta columna.
matriz[2:,:] #Devuelve los elementos a partir de la segunda fila para todas las columnas.
matriz[::2,::3] #Devuelve las filas de la primera a la última con pasos de 2 posiciones y de la primera a la última columna con pasos de 3 posiciones.
```





**3.2. Ejercicios**

1. Escriba una función que reciba como argumento una matriz de numpy (array), obtenga todos los elementos de la diagonal de una matriz de NxN y los retorne en un array de NumPy.

In [ ]:
import numpy as np

def obtener_diagonal(matriz):
    
    return np.diagonal(matriz)

# Ejemplo de uso
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

diagonal = obtener_diagonal(matriz)
print("Diagonal:", diagonal)

2. Escriba una función que reciba como argumentos una matriz de NxN y un número de fila y retorne la multiplicación de todos los elementos de determinada fila.

In [ ]:
import numpy as np

def multiplicar_fila(matriz, fila):

    return np.prod(matriz[fila, :])

# Ejemplo de uso
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

fila = 1  # Segunda fila (índice 1)
resultado = multiplicar_fila(matriz, fila)
print(f"Producto de la fila {fila}: {resultado}")

3. Escriba una función que reciba como argumentos una matriz de NxN y un número de columna y retorne la suma de todos los elementos de determinada columna.

In [ ]:
import numpy as np

def sumar_columna(matriz, columna):

    return np.sum(matriz[:, columna])

# Ejemplo de uso
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

columna = 2  # Tercera columna (índice 2)
resultado = sumar_columna(matriz, columna)
print(f"Suma de la columna {columna}: {resultado}")

4. Escriba una función que reciba como argumento una matriz y retorne su transpuesta.

In [ ]:
import numpy as np

def transponer_matriz(matriz):

    return matriz.T

# Ejemplo de uso
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matriz_transpuesta = transponer_matriz(matriz)

print("\nMatriz transpuesta:")
print(matriz_transpuesta)


**3.3. Tipos especiales de matrices en NumPy**

De igual manera, se pueden crear ciertos tipos de matriz especiales utilizando NumPy mediante el uso del argumento shape visto anteriormente. Algunas matrices pueden ser:

**Matriz donde todos sus elementos son 0:** Esta matriz puede ser creada utilizando la función *np.zeros()* donde como argumento *shape* se debe indicar las dimensiones con las que se quiere construir la matriz.

**Matriz donde todos sus elementos son 1:** Esta matriz puede ser creada utilizando la función *np.ones()* donde como argumento *shape* se debe indicar las dimensiones con las que se quiere construir la matriz.

**Matriz identidad:** Esta matriz puede ser creada utilizando la función *np.eye* donde como argumento obligatorio se debe indicar N, el número de filas, y como argumento opcional se puede indicar M (número de columnas) y/o k (posición de la diagonal, donde 0 indica la diagonal principal, un número positivo indica una diagonal superior y un número negativo indica una diagonal inferior).

**3.4. Ejercicios**

1. Cree un vector de 15 elementos donde todos sus elementos son el número 1 e imprima sus dimensiones.


In [ ]:
import numpy as np

# Crear un vector de 15 elementos con el valor 1
vector = np.ones(15)

# Imprimir el vector
print("Vector:")
print(vector)

# Imprimir las dimensiones del vector
print("\nDimensiones del vector:")
print(vector.shape)


2. Cree una matriz de 3 filas por 6 columnas donde todos sus elementos sean el número 0.


In [ ]:
import numpy as np

# Crear una matriz de 3x6 con todos sus elementos en 0
matriz = np.zeros((3, 6))

# Imprimir la matriz
print("Matriz:")
print(matriz)



3. Cree una matriz de 8x8 donde todos los elementos de la diagonal principal son el número 1 y los demás son el número 0.



In [ ]:
import numpy as np

# Crear una matriz de 8x8 con 1 en la diagonal principal y 0 en los demás elementos
matriz = np.eye(8)

# Imprimir la matriz
print("Matriz 8x8 con 1 en la diagonal principal:")
print(matriz)


4. Cree una función que reciba como argumento una matriz y retorne el promedio por filas de sus elementos.

    **Hint:** ¿Que función tiene el parámetro axis dentro de la función np.mean()?

In [ ]:
import numpy as np

# Crear una matriz de 8x8 con 1 en la diagonal principal y 0 en los demás elementos
matriz = np.eye(8)

# Imprimir la matriz
print("Matriz 8x8 con 1 en la diagonal principal:")
print(matriz)


5. Cree una función que reciba como argumento una matriz y retorne el promedio por columnas de sus elementos.

    **Hint:** ¿Que función tiene el parámetro axis dentro de la función np.mean()?

In [ ]:
import numpy as np

def promedio_por_columnas(matriz):

    return np.mean(matriz, axis=0)

# Ejemplo de uso
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

promedios = promedio_por_columnas(matriz)
print("Promedios por columnas:")
print(promedios)


#**4. Propiedades y operaciones con matrices**

NumPy permite realizar distintas operaciones con matrices, entre las principales se encuentran:

```
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
```
- **Suma de matrices**: La suma de matrices elemento a elemento se realiza sumando las dos matrices como dos variables estandar.
```
c = a + b
[[ 6  8]
 [10 12]]
```
- **Resta de matrices**: La resta de matrices elemento a elemento se realiza restando las dos matrices como dos variables estandar.
```
c = a - b
[[-4 -4]
 [-4 -4]]
```
- **División de matrices**: La división de matrices elemento a elemento se realiza dividiendo las dos matrices como dos variables estandar (esto también incluye la división entera y la operación módulo).
```
c = a / b
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
```

- **Multiplicación de matrices (elemento a elemento)**: La multiplicación de matrices elemento a elemento se realiza multiplicando las dos matrices como dos variables estandar.
```
c = a * b
[[ 5 12]
 [21 32]]
```

- **Producto matricial**: El producto entre matrices se puede realizar de varias formas, algunas de ellas incluyen el símbolo '@' como operador. Bajo esta implementación Numpy se ajusta automáticamente a los distintos tipos de producto que se dan a lugar entre vectores y matrices.

Importante: 
Si los dos objetos son vectores, se hace un producto punto al usar el operador '@'. Es equivalente usar la función *numpy.dot()*.
Si los dos objetos son matrices, y satisfacen la relación necesaria entre filas y columnas de esta operación, se hace un producto matricial al usar el operador '@'. Es equivalente a usar la función *numpy.matmul()*.
En la versión reciente de Numpy, se ha extendido el uso de np.dot() y np.matmul() de modo que ahora es completamente equivalente usar cualquiera de las tres aproximaciones: '@', *numpy.dot()*. ó *numpy.matmul()*.
```
c = a @ b
[[19 22]
 [43 50]]
c = np.dot(a,b)
[[19 22]
 [43 50]]
```






**4.1. Ejercicios**

Para las siguientes parejas de matrices determine:

- Suma de las matrices elemento a elemento.

- Resta de las matrices elemento a elemento.

- División de las matrices elemento a elemento.

- Multiplicación de las matrices elemento a elemento.

- Producto matricial.

**Pareja 1:**

\begin{align}
 \begin{pmatrix}
 10 & 2 & 1 & \\
 24 & 1 & 2 & \\
 2 & 3 & 2 & \\
\end{pmatrix}  
 \begin{pmatrix}
 3 & 7 & 8 & \\
 2 & 1 & 3 & \\
 7 & 9 & 8 & \\
\end{pmatrix}
\end{align}


In [ ]:
import numpy as np 

matrix1 = np.array([[10,2,1],[24,1,2],[2,3,2]])
matrix2 = np.array([[3,7,8],[2,1,3],[7,9,8]])

e_wise_sum = matrix1 + matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[10,2,1],[24,1,2],[2,3,2]])
matrix2 = np.array([[3,7,8],[2,1,3],[7,9,8]])

e_wise_sub = matrix1 - matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[10,2,1],[24,1,2],[2,3,2]])
matrix2 = np.array([[3,7,8],[2,1,3],[7,9,8]])

e_wise_div = matrix1 / matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[10,2,1],[24,1,2],[2,3,2]])
matrix2 = np.array([[3,7,8],[2,1,3],[7,9,8]])

e_wise_prod = matrix1 * matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[10,2,1],[24,1,2],[2,3,2]])
matrix2 = np.array([[3,7,8],[2,1,3],[7,9,8]])

matrix_prod = np.dot(matrix1,matrix2)


**Pareja 2:**

\begin{align}
 \begin{pmatrix}
 9 & 4 & 7 & \\
 4 & 6 & 2 & \\
 2 & 8 & 5 & \\
\end{pmatrix}
 \begin{pmatrix}
 1 & 2 & 4 & \\
 6 & 7 & 5 & \\
 16 & 14 & 7 & \\
\end{pmatrix}
\end{align}

In [ ]:
import numpy as np 

matrix1 = np.array([[9,4,7],[4,6,2],[2,8,5]])
matrix2 = np.array([[1,2,4],[6,7,5],[16,14,7]])

e_wise_sum = matrix1 + matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[9,4,7],[4,6,2],[2,8,5]])
matrix2 = np.array([[1,2,4],[6,7,5],[16,14,7]])

e_wise_sub = matrix1 - matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[9,4,7],[4,6,2],[2,8,5]])
matrix2 = np.array([[1,2,4],[6,7,5],[16,14,7]])

e_wise_div = matrix1 / matrix2

In [ ]:
import numpy as np 

matrix1 = np.array([[9,4,7],[4,6,2],[2,8,5]])
matrix2 = np.array([[1,2,4],[6,7,5],[16,14,7]])

e_wise_prod = matrix1 * matrix2

In [1]:
import numpy as np 

matrix1 = np.array([[9,4,7],[4,6,2],[2,8,5]])
matrix2 = np.array([[1,2,4],[6,7,5],[16,14,7]])

matrix_prod = np.dot(matrix1,matrix2)

#**5. Operaciones de álgebra lineal**

Numpy permite realizar ciertas operaciones de álgebra lineal haciendo uso de su paquete linalg, hoy observaremos algunas de las principales operaciones que pueden ser realizadas con NumPy.

**np.linalg.det:** Calcula el determinante de un array que debe ser de MxM.

**np.linalg.inv:** Calcula la inversa de un array que debe ser de MxM y retorna un error si la conversión falla o el array no tiene MxM elementos.

**np.linalg.eig:** Calcula los eigenvalores y eigenvectores de un array que debe ser de MxM y los retorna en la forma (W,v) donde W es un array que contiene los eigenvalores y v un array que contiene los eigenvectores.

**5.1. Ejercicios**

1. Para cada una de las siguientes matrices:

    a. Determine el número de dimensiones de la matriz.

    b. Determine las dimensiones de la matriz.

    c. Calcule el determinante de la matriz.

    d. Calcule la inversa de la matriz.      

    e. Calcule los valores y vectores propios, e imprímalos en pantalla de la siguiente manera:

  Eigenvalor 1: valor, Eigenvector 1: $[1,2...]$

Matriz 1

\begin{align}
 \begin{pmatrix}
 1 & 8 & 2 \\
 3 & 4 & 5 \\
 5 & 1 & 10 \\
\end{pmatrix}
 \end{align}


Matriz 2

\begin{align}
 \begin{pmatrix}
 7 & 6 & 3 \\
 2 & 9 & 5 \\
 3 & 7 & 10 \\
\end{pmatrix}
 \end{align}


Matriz 3

\begin{align}
 \begin{pmatrix}
 10 & 8 & 1 \\
 6 & 2 & 7 \\
 8 & 9 & 4 \\
\end{pmatrix}
 \end{align}

In [ ]:
import numpy as np
matrix1 = np.array([[1,8,2],[3,4,5],[5,1,10]])
matrix2 = np.array([[7,6,3],[2,9,5],[3,7,10]])
matrix3 = np.array([[10,8,1],[6,2,7],[8,9,4]])

def matrix_operations(matrix):
    # a.
    print("Número de dimensiones:", matrix.ndim)
    # b. 
    print("Dimensiones de la matriz:", matrix.shape)
    # c.
    det = np.linalg.det(matrix)
    print("Determinante:", det)
    # d. Calculate the inverse of the matrix (if it exists)
    try:
        inv = np.linalg.inv(matrix)
        print("Inversa de la matriz:\n", inv)
    except np.linalg.LinAlgError:
        print("La matriz no tiene inversa.")
    # e. Calculate eigenvalues and eigenvectors
    eigvals, eigvecs = np.linalg.eig(matrix)
    print("Valores propios:", eigvals)
    print("Vectores propios:\n", eigvecs)
    print("====================================")

print("Operaciones para matrix1:")
matrix_operations(matrix1)

print("Operaciones para matrix2:")
matrix_operations(matrix2)

print("Operaciones para matrix3:")
matrix_operations(matrix3)


#**6. Arange vs linspace**

Otros dos métodos conocidos para la creación de arrays son np.arange y np.linspace. Estos métodos son usados especialmente cuando se busca crear arrays que representen una secuencia temporal, como por ejemplo un array representando la variable del tiempo que va de 0 a 50 segundos con pasos de 1 segundo. Ambos métodos reciben como argumentos obligatorios el número de inicio y el número de fin. La principal diferencia entre estos métodos se da en que np.arange recibe como tercer argumento los intervalos para los que se quiere la muestra. Por ejemplo, si se quiere crear un array de 0 a 50 con pasos de 1, la síntesis del código debería ser:

```
array = np.arange(0,51,1)
```
Por otra parte, linspace recibe como tercer argumento el número de muestras que se quiere en el array. Es decir, si se quiere que el array sea de 1 a 50 con pasos de 1 (50 muestras) la síntesis del código debería ser:



```
array = np.linspace(0,50,51)
```

**Nota:** Es importante diferenciar el tipo de dato que contiene el array, ya que en el caso del ejemplo de arange, como se están utilizando pasos enteros (de 1 en 1) el retorno es un array con números en tipo int32, mientras que en el caso del ejemplo de linspace el retorno se da en float64. Comúnmente se trabaja con float64 en NumPy, así que si quisieramos que el retorno del ejemplo de arange sea en formato float64 basta con cambiar el número de pasos a uno que no sea entero o a definir con un punto al final cada número como a continuación:


```
array = np.arange(0., 51., 1)
```




**6.1. Ejercicios**

1. Defina un array que contenga números de 10 a 20 con pasos de 0.25 e imprima su longitud.


In [ ]:
import numpy as np
arr = np.arange(10,20,0.25)
print(len(arr))


2. Defina un array que contenga números de 1 a 5 y que contenga 100 elementos.


In [ ]:
import numpy as np
arr = np.linspace(1, 5, 100)


3. Defina dos arrays con los límites de su preferencia (deben ser los mismos para ambos arrays) utilizando los dos métodos de tal manera que ambos arrays tengan el mismo número de datos e imprima su longitud.

In [ ]:
import numpy as np
arr1 = np.arange(0,10,1)
arr2 = np.arange(0,10,1)

print("Length first array: " + str(len(arr1)))
print("Length second array: " + str(len(arr2)))